### ISSUE TITLE
Fails with CSS comments

### ISSUE THREAD

**Issue by zraineri** [wizardpisces/tiny-sass-compiler#2]
Love package, honestly really appreciate your work!

I noticed it throws an error when using comments, for example:
```scss
/* Class created by [x] */
.testClass {
  color: blue;
}
```

Am I doing something wrong or is handling comments just not a feature?
